# Training parameters
num_epochs: 100
batch_size: 32
learning_rate: 0.0002
lambda_l1: 100.0  # Weight for L1 loss

# Model parameters
embedding_dim: 512
noise_dim: 100
channels: 3

# Training settings
num_workers: 4
save_interval: 5  # Save checkpoint every N epochs
fid_interval: 10  # Calculate FID every N epochs

# Weights & Biases settings
project_name: "face-conditional-gan" 